SET NAMES utf8mb4;

-- Agent platform database schema
-- Assumption: MySQL 8.0+
-- Convention:
-- 1. String IDs are used to align with runtime-generated identifiers such as run_123 / step_456.
-- 2. JSON fields are used for policy, payload, and schema-like content.
-- 3. Logical deletion is implemented through deleted.
-- 4. Every table includes the required audit columns:
--    last_modifier, last_modify_time, last_modifier_name,
--    create_time, creator_name, creator, deleted

CREATE TABLE IF NOT EXISTS agent_definition (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    code VARCHAR(128) NOT NULL COMMENT 'Stable agent code',
    name VARCHAR(256) NOT NULL COMMENT 'Agent name',
    description TEXT NULL COMMENT 'Agent description',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether current record is enabled',
    current_version INT NOT NULL DEFAULT 1 COMMENT 'Current published version',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Last modifier id',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Last modify time',
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Last modifier name',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Create time',
    creator_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Creator name',
    creator VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Creator id',
    deleted TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Logical delete flag',
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_definition_code (code),
    KEY idx_agent_definition_enabled (enabled),
    KEY idx_agent_definition_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Agent definition master table';

CREATE TABLE IF NOT EXISTS agent_definition_version (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    agent_definition_id VARCHAR(64) NOT NULL COMMENT 'Reference to agent_definition.id',
    version INT NOT NULL COMMENT 'Version number',
    status VARCHAR(32) NOT NULL DEFAULT 'draft' COMMENT 'draft/published/offline',
    name VARCHAR(256) NOT NULL COMMENT 'Snapshot name',
    description TEXT NULL COMMENT 'Snapshot description',
    instruction TEXT NULL COMMENT 'Agent instruction',
    system_prompt_template LONGTEXT NULL COMMENT 'System prompt template',
    default_model VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Default model name',
    allowed_tools JSON NULL COMMENT 'Allowed tool names',
    knowledge_sources JSON NULL COMMENT 'Bound knowledge sources',
    memory_policy JSON NULL COMMENT 'Memory strategy',
    routing_policy JSON NULL COMMENT 'Routing strategy',
    approval_policy JSON NULL COMMENT 'Approval strategy',
    execution_policy JSON NULL COMMENT 'Execution strategy',
    planner_policy JSON NULL COMMENT 'Planner strategy',
    context_policy JSON NULL COMMENT 'Context assembly strategy',
    allowed_handoffs JSON NULL COMMENT 'Allowed target agents',
    output_schema JSON NULL COMMENT 'Expected response schema',
    max_turns INT NOT NULL DEFAULT 8 COMMENT 'Max turns',
    max_cost DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT 'Max cost limit',
    published_at DATETIME(3) NULL COMMENT 'Publish time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_agent_def_ver (agent_definition_id, version),
    KEY idx_agent_def_ver_status (status),
    KEY idx_agent_def_ver_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Versioned snapshot of an agent definition';

CREATE TABLE IF NOT EXISTS tool_definition (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tool_name VARCHAR(128) NOT NULL COMMENT 'Tool unique name',
    display_name VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'Display name',
    description TEXT NULL COMMENT 'Tool description',
    input_schema JSON NULL COMMENT 'Input JSON schema',
    output_schema JSON NULL COMMENT 'Output JSON schema',
    side_effect_level VARCHAR(32) NOT NULL DEFAULT 'read_only' COMMENT 'read_only/internal_write/external_write/destructive',
    timeout_ms INT NOT NULL DEFAULT 30000 COMMENT 'Timeout in milliseconds',
    retry_policy JSON NULL COMMENT 'Retry policy',
    auth_policy JSON NULL COMMENT 'Authorization policy',
    idempotency_policy JSON NULL COMMENT 'Idempotency policy',
    async_supported TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether async mode is supported',
    consistency_mode VARCHAR(32) NOT NULL DEFAULT 'eventual' COMMENT 'Consistency mode',
    compensation_policy JSON NULL COMMENT 'Compensation policy for side effects',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether tool is enabled',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_tool_definition_name (tool_name),
    KEY idx_tool_definition_effect (side_effect_level),
    KEY idx_tool_definition_enabled (enabled),
    KEY idx_tool_definition_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tool registry metadata';

CREATE TABLE IF NOT EXISTS route_rule (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    agent_definition_version_id VARCHAR(64) NOT NULL COMMENT 'Source agent definition version',
    source_agent_code VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Source agent code',
    target_agent_code VARCHAR(128) NOT NULL COMMENT 'Target agent code',
    rule_name VARCHAR(128) NOT NULL COMMENT 'Rule name',
    priority INT NOT NULL DEFAULT 100 COMMENT 'Rule priority, smaller means higher',
    match_type VARCHAR(64) NOT NULL DEFAULT 'intent' COMMENT 'intent/tag/schema/manual',
    match_expression JSON NULL COMMENT 'Structured route condition',
    handoff_mode VARCHAR(32) NOT NULL DEFAULT 'route_only' COMMENT 'route_only/delegate_and_wait/delegate_and_merge',
    context_scope JSON NULL COMMENT 'Context scope override',
    tool_scope JSON NULL COMMENT 'Tool scope override',
    knowledge_scope JSON NULL COMMENT 'Knowledge scope override',
    approval_required TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Whether route requires approval',
    enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether rule is enabled',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_route_rule_source (source_agent_code),
    KEY idx_route_rule_target (target_agent_code),
    KEY idx_route_rule_priority (priority),
    KEY idx_route_rule_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Routing and handoff rules';

CREATE TABLE IF NOT EXISTS agent_run (
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    agent_code VARCHAR(128) NOT NULL COMMENT 'Agent code',
    agent_definition_version_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Bound definition version',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    user_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'End user id',
    session_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Session id',
    status VARCHAR(32) NOT NULL COMMENT 'Created/Running/WaitingTool/WaitingApproval/WaitingHuman/Suspended/Completed/Failed/Cancelled/TimedOut',
    input_payload JSON NULL COMMENT 'Original input',
    output_payload JSON NULL COMMENT 'Final output',
    current_step_no INT NOT NULL DEFAULT 0 COMMENT 'Current step number',
    parent_run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Parent run id',
    root_run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Root run id',
    delegated_by_run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Delegating parent run id',
    delegated_by_agent VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Delegating agent code',
    status_version BIGINT NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    idempotency_key VARCHAR(128) NOT NULL COMMENT 'Client idempotency key',
    current_wait_token VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Current wait token',
    interrupt_reason VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'Interrupt reason',
    max_turns INT NOT NULL DEFAULT 0 COMMENT 'Execution turn cap snapshot',
    max_cost DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT 'Execution cost cap snapshot',
    total_cost DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT 'Accumulated cost',
    started_at DATETIME(3) NULL COMMENT 'Run start time',
    ended_at DATETIME(3) NULL COMMENT 'Run end time',
    last_heartbeat_at DATETIME(3) NULL COMMENT 'Last heartbeat time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (run_id),
    UNIQUE KEY uk_agent_run_idempotency (idempotency_key),
    KEY idx_agent_run_root_run (root_run_id),
    KEY idx_agent_run_parent_run (parent_run_id),
    KEY idx_agent_run_status (status),
    KEY idx_agent_run_tenant_session (tenant_id, session_id),
    KEY idx_agent_run_user (user_id),
    KEY idx_agent_run_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Runtime run instance';

CREATE TABLE IF NOT EXISTS agent_step (
    step_id VARCHAR(64) NOT NULL COMMENT 'Step id',
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    step_no INT NOT NULL COMMENT 'Step number',
    step_type VARCHAR(32) NOT NULL COMMENT 'Input/Plan/Reason/ToolCall/ToolResult/Retrieve/Handoff/ApprovalRequest/ApprovalResult/Summarize/Respond/Interrupt',
    status VARCHAR(32) NOT NULL COMMENT 'Pending/Running/Succeeded/Failed/Skipped/Cancelled/TimedOut',
    input_payload JSON NULL COMMENT 'Input payload',
    output_payload JSON NULL COMMENT 'Output payload',
    error_payload JSON NULL COMMENT 'Error payload',
    step_key VARCHAR(128) NOT NULL COMMENT 'Idempotent step key',
    retry_count INT NOT NULL DEFAULT 0 COMMENT 'Retry count',
    depends_on_step_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Dependency step id',
    decision_payload JSON NULL COMMENT 'Structured decision payload',
    status_version BIGINT NOT NULL DEFAULT 0 COMMENT 'Optimistic lock version',
    started_at DATETIME(3) NULL COMMENT 'Start time',
    ended_at DATETIME(3) NULL COMMENT 'End time',
    duration_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Duration in ms',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (step_id),
    UNIQUE KEY uk_agent_step_run_key (run_id, step_key),
    UNIQUE KEY uk_agent_step_run_no (run_id, step_no),
    KEY idx_agent_step_type (step_type),
    KEY idx_agent_step_status (status),
    KEY idx_agent_step_depends (depends_on_step_id),
    KEY idx_agent_step_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Atomic step inside a run';

CREATE TABLE IF NOT EXISTS agent_message (
    message_id VARCHAR(64) NOT NULL COMMENT 'Message id',
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Related step id',
    role VARCHAR(32) NOT NULL COMMENT 'system/developer/user/assistant/tool_call/tool_result/handoff/approval_request/approval_result/summary',
    message_type VARCHAR(32) NOT NULL DEFAULT 'normal' COMMENT 'normal/stream_delta/summary/citation',
    seq_no BIGINT NOT NULL DEFAULT 0 COMMENT 'Message sequence inside run',
    content LONGTEXT NULL COMMENT 'Text content',
    content_json JSON NULL COMMENT 'Structured message content',
    source_ref VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'Source reference',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Business message time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (message_id),
    UNIQUE KEY uk_agent_message_run_seq (run_id, seq_no),
    KEY idx_agent_message_run_created (run_id, created_at),
    KEY idx_agent_message_step (step_id),
    KEY idx_agent_message_role (role),
    KEY idx_agent_message_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Conversation and runtime message log';

CREATE TABLE IF NOT EXISTS agent_approval (
    approval_id VARCHAR(64) NOT NULL COMMENT 'Approval id',
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL COMMENT 'Approval request step id',
    requested_action VARCHAR(256) NOT NULL COMMENT 'Action to approve',
    risk_level VARCHAR(32) NOT NULL DEFAULT 'medium' COMMENT 'low/medium/high/critical',
    request_payload JSON NULL COMMENT 'Approval request content',
    decision VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/approved/rejected/expired/cancelled',
    approver_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Approver id',
    approver_role VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Approver role',
    approver_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Approver name',
    comment VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Approval comment',
    wait_token VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Resume token',
    expires_at DATETIME(3) NULL COMMENT 'Expire time',
    decided_at DATETIME(3) NULL COMMENT 'Decision time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (approval_id),
    KEY idx_agent_approval_run (run_id),
    KEY idx_agent_approval_step (step_id),
    KEY idx_agent_approval_decision (decision),
    KEY idx_agent_approval_expires (expires_at),
    KEY idx_agent_approval_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Approval and human-in-the-loop records';

CREATE TABLE IF NOT EXISTS tool_invocation (
    invocation_id VARCHAR(64) NOT NULL COMMENT 'Invocation id',
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL COMMENT 'Step id',
    tool_name VARCHAR(128) NOT NULL COMMENT 'Tool name',
    mode VARCHAR(16) NOT NULL DEFAULT 'sync' COMMENT 'sync/async',
    status VARCHAR(32) NOT NULL COMMENT 'Pending/Running/Succeeded/Failed/Expired/Cancelled',
    input_payload JSON NULL COMMENT 'Invocation input',
    output_payload JSON NULL COMMENT 'Invocation output',
    error_payload JSON NULL COMMENT 'Invocation error',
    idempotency_key VARCHAR(128) NOT NULL COMMENT 'Idempotency key',
    callback_token VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Async callback token',
    executor_node VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Executor node',
    started_at DATETIME(3) NULL COMMENT 'Start time',
    ended_at DATETIME(3) NULL COMMENT 'End time',
    duration_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Duration in ms',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (invocation_id),
    UNIQUE KEY uk_tool_invocation_idempotency (idempotency_key),
    KEY idx_tool_invocation_run (run_id),
    KEY idx_tool_invocation_step (step_id),
    KEY idx_tool_invocation_tool_status (tool_name, status),
    KEY idx_tool_invocation_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tool invocation record';

CREATE TABLE IF NOT EXISTS idempotency_record (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    scope_type VARCHAR(32) NOT NULL COMMENT 'run/step/tool/callback/api',
    scope_key VARCHAR(128) NOT NULL COMMENT 'Business unique scope key',
    request_hash VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Request hash',
    target_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Bound target id',
    status VARCHAR(32) NOT NULL DEFAULT 'created' COMMENT 'created/processed/failed',
    expire_at DATETIME(3) NULL COMMENT 'Record expiration time',
    extra_payload JSON NULL COMMENT 'Additional context',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_idempotency_scope (scope_type, scope_key),
    KEY idx_idempotency_target (target_id),
    KEY idx_idempotency_expire (expire_at),
    KEY idx_idempotency_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Reusable idempotency registry';

CREATE TABLE IF NOT EXISTS run_outbox_event (
    event_id VARCHAR(64) NOT NULL COMMENT 'Event id',
    run_id VARCHAR(64) NOT NULL COMMENT 'Run id',
    seq_no BIGINT NOT NULL COMMENT 'Strictly increasing sequence inside run',
    event_type VARCHAR(64) NOT NULL COMMENT 'run.created/message.delta/step.started/step.completed/tool.called/tool.completed/approval.requested/approval.resolved/run.completed/run.failed',
    run_status VARCHAR(32) NOT NULL COMMENT 'Run status snapshot',
    payload JSON NULL COMMENT 'Event payload',
    publish_status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/published/failed',
    published_at DATETIME(3) NULL COMMENT 'Publish time',
    retry_count INT NOT NULL DEFAULT 0 COMMENT 'Publish retry count',
    occurred_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Business occurrence time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (event_id),
    UNIQUE KEY uk_outbox_run_seq (run_id, seq_no),
    KEY idx_outbox_publish_status (publish_status),
    KEY idx_outbox_event_type (event_type),
    KEY idx_outbox_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Transactional outbox for run events';

CREATE TABLE IF NOT EXISTS model_call_log (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Step id',
    model_name VARCHAR(128) NOT NULL COMMENT 'Model name',
    provider_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Model provider',
    request_mode VARCHAR(32) NOT NULL DEFAULT 'chat' COMMENT 'chat/json/tool_call/planner',
    request_payload JSON NULL COMMENT 'Sanitized request payload',
    response_payload JSON NULL COMMENT 'Sanitized response payload',
    prompt_tokens INT NOT NULL DEFAULT 0 COMMENT 'Prompt tokens',
    completion_tokens INT NOT NULL DEFAULT 0 COMMENT 'Completion tokens',
    total_tokens INT NOT NULL DEFAULT 0 COMMENT 'Total tokens',
    latency_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Latency in ms',
    cost_amount DECIMAL(18,6) NOT NULL DEFAULT 0 COMMENT 'Cost',
    finish_reason VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'completed/tool_call/handoff/max_turns',
    success_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether successful',
    error_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Error code',
    error_message VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Error message',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_model_call_run (run_id),
    KEY idx_model_call_step (step_id),
    KEY idx_model_call_model (model_name),
    KEY idx_model_call_provider (provider_name),
    KEY idx_model_call_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Model invocation audit log';

CREATE TABLE IF NOT EXISTS tool_execution_log (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    invocation_id VARCHAR(64) NOT NULL COMMENT 'Reference tool_invocation.invocation_id',
    run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Step id',
    tool_name VARCHAR(128) NOT NULL COMMENT 'Tool name',
    request_payload JSON NULL COMMENT 'Sanitized request payload',
    response_payload JSON NULL COMMENT 'Sanitized response payload',
    latency_ms BIGINT NOT NULL DEFAULT 0 COMMENT 'Latency in ms',
    success_flag TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Whether successful',
    error_code VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Error code',
    error_message VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Error message',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_tool_execution_invocation (invocation_id),
    KEY idx_tool_execution_run (run_id),
    KEY idx_tool_execution_step (step_id),
    KEY idx_tool_execution_tool (tool_name),
    KEY idx_tool_execution_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Tool execution audit log';

CREATE TABLE IF NOT EXISTS policy_audit_log (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Run id',
    step_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Step id',
    policy_type VARCHAR(64) NOT NULL COMMENT 'tenant/agent/tool/approval/security',
    policy_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Policy name',
    decision VARCHAR(32) NOT NULL COMMENT 'allow/deny/review/degrade',
    input_payload JSON NULL COMMENT 'Policy evaluation input',
    result_payload JSON NULL COMMENT 'Policy evaluation result',
    reason VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Reason summary',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_policy_audit_run (run_id),
    KEY idx_policy_audit_step (step_id),
    KEY idx_policy_audit_type (policy_type),
    KEY idx_policy_audit_decision (decision),
    KEY idx_policy_audit_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Policy evaluation audit log';

CREATE TABLE IF NOT EXISTS knowledge_document (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    knowledge_source_code VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Knowledge source code',
    document_code VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'External document code',
    title VARCHAR(512) NOT NULL COMMENT 'Document title',
    source_uri VARCHAR(1024) NOT NULL DEFAULT '' COMMENT 'Source uri',
    content_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'file/web/faq/sop/ticket',
    metadata JSON NULL COMMENT 'Document metadata',
    parse_status VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT 'pending/parsed/failed',
    version_no INT NOT NULL DEFAULT 1 COMMENT 'Document version',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_knowledge_document_tenant (tenant_id),
    KEY idx_knowledge_document_source (knowledge_source_code),
    KEY idx_knowledge_document_code (document_code),
    KEY idx_knowledge_document_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Knowledge document metadata';

CREATE TABLE IF NOT EXISTS knowledge_chunk (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    document_id VARCHAR(64) NOT NULL COMMENT 'Document id',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    chunk_no INT NOT NULL COMMENT 'Chunk sequence',
    content MEDIUMTEXT NOT NULL COMMENT 'Chunk content',
    token_count INT NOT NULL DEFAULT 0 COMMENT 'Token count',
    source VARCHAR(512) NOT NULL DEFAULT '' COMMENT 'Source marker',
    metadata JSON NULL COMMENT 'Chunk metadata',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_knowledge_chunk_doc_no (document_id, chunk_no),
    KEY idx_knowledge_chunk_tenant (tenant_id),
    KEY idx_knowledge_chunk_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Chunked knowledge content';

CREATE TABLE IF NOT EXISTS embedding_index (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    source_type VARCHAR(32) NOT NULL COMMENT 'knowledge_chunk/session_memory/user_memory/summary_memory',
    source_id VARCHAR(64) NOT NULL COMMENT 'Source record id',
    model_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Embedding model',
    vector_ref VARCHAR(256) NOT NULL DEFAULT '' COMMENT 'Reference to external vector store entry',
    vector_payload JSON NULL COMMENT 'Optional inline vector payload',
    metadata JSON NULL COMMENT 'Embedding metadata',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_embedding_source (source_type, source_id),
    KEY idx_embedding_tenant (tenant_id),
    KEY idx_embedding_model (model_name),
    KEY idx_embedding_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Embedding index metadata';

CREATE TABLE IF NOT EXISTS session_memory (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    user_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'User id',
    session_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Session id',
    run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Related run id',
    memory_type VARCHAR(32) NOT NULL DEFAULT 'recent_context' COMMENT 'recent_context/tool_result/summary',
    content_json JSON NULL COMMENT 'Structured memory content',
    source_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'user/tool/system/human',
    source_ref VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Source reference',
    confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000 COMMENT 'Confidence score',
    expires_at DATETIME(3) NULL COMMENT 'Expiration time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_session_memory_session (tenant_id, session_id),
    KEY idx_session_memory_user (tenant_id, user_id),
    KEY idx_session_memory_run (run_id),
    KEY idx_session_memory_expires (expires_at),
    KEY idx_session_memory_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Short-term session memory';

CREATE TABLE IF NOT EXISTS user_memory (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    user_id VARCHAR(64) NOT NULL COMMENT 'User id',
    memory_key VARCHAR(128) NOT NULL COMMENT 'Business memory key',
    memory_scope VARCHAR(64) NOT NULL DEFAULT 'user' COMMENT 'user/account/tenant',
    memory_type VARCHAR(32) NOT NULL DEFAULT 'preference' COMMENT 'preference/fact/profile',
    memory_value JSON NULL COMMENT 'Memory value',
    source_type VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'human/tool/user',
    source_ref VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Source reference',
    confidence DECIMAL(5,4) NOT NULL DEFAULT 1.0000 COMMENT 'Confidence score',
    effective_at DATETIME(3) NULL COMMENT 'Effective time',
    expires_at DATETIME(3) NULL COMMENT 'Expiration time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_user_memory_key (tenant_id, user_id, memory_key),
    KEY idx_user_memory_scope (memory_scope),
    KEY idx_user_memory_type (memory_type),
    KEY idx_user_memory_expires (expires_at),
    KEY idx_user_memory_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Long-term user memory';

CREATE TABLE IF NOT EXISTS summary_memory (
    id VARCHAR(64) NOT NULL COMMENT 'Primary key',
    tenant_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Tenant id',
    run_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Run id',
    session_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT 'Session id',
    summary_type VARCHAR(32) NOT NULL DEFAULT 'conversation' COMMENT 'conversation/task/progress',
    source_start_seq BIGINT NOT NULL DEFAULT 0 COMMENT 'Source start sequence',
    source_end_seq BIGINT NOT NULL DEFAULT 0 COMMENT 'Source end sequence',
    summary_text MEDIUMTEXT NOT NULL COMMENT 'Summary text',
    summary_json JSON NULL COMMENT 'Structured summary',
    generated_by_model VARCHAR(128) NOT NULL DEFAULT '' COMMENT 'Model used to generate summary',
    generated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'Generation time',
    expires_at DATETIME(3) NULL COMMENT 'Expiration time',
    last_modifier VARCHAR(64) NOT NULL DEFAULT '',
    last_modify_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    last_modifier_name VARCHAR(128) NOT NULL DEFAULT '',
    create_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    creator_name VARCHAR(128) NOT NULL DEFAULT '',
    creator VARCHAR(64) NOT NULL DEFAULT '',
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    KEY idx_summary_memory_run (run_id),
    KEY idx_summary_memory_session (tenant_id, session_id),
    KEY idx_summary_memory_range (source_start_seq, source_end_seq),
    KEY idx_summary_memory_expires (expires_at),
    KEY idx_summary_memory_deleted (deleted)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Summary memory for long context compression';
