namespace BestAgent.Api.Contracts.Tools;

public record UpdateToolDefinitionRequest(
    string DisplayName,
    string? Description,
    string? InputSchema,
    string? OutputSchema,
    string? ExecutionKind,
    string? ExecutionBinding,
    string? EndpointUrl,
    string? HttpMethod,
    string? AuthHeaders,
    string? CallbackSecret,
    string SideEffectLevel,
    int TimeoutMs,
    string? RetryPolicy,
    string? AuthPolicy,
    string? IdempotencyPolicy,
    bool AsyncSupported,
    string ConsistencyMode,
    string? CompensationPolicy,
    bool Enabled,
    ToolExecutionRequest? Execution = null,
    ToolPoliciesRequest? Policies = null,
    string? ParameterPolicy = null);
