namespace BestAgent.Application.AgentDefinitions;

public record AgentDefinitionViewModel(
    string Code,
    string Name,
    string? Description,
    bool Enabled,
    int CurrentVersion,
    string VersionId,
    int Version,
    string VersionStatus,
    string VersionName,
    string? VersionDescription,
    string? Instruction,
    string? SystemPromptTemplate,
    string DefaultModel,
    IReadOnlyList<string> AllowedTools,
    IReadOnlyList<string> KnowledgeSources,
    string? MemoryPolicy,
    string? RoutingPolicy,
    string? ApprovalPolicy,
    string? ExecutionPolicy,
    string? PlannerPolicy,
    string? ContextPolicy,
    IReadOnlyList<string> AllowedHandoffs,
    string? OutputSchema,
    int MaxTurns,
    decimal MaxCost,
    DateTime CreateTime,
    DateTime LastModifyTime,
    DateTime? PublishedAt,
    IReadOnlyList<string>? DeniedTools = null)
{
    public static AgentDefinitionViewModel FromResolvedDefinition(Domain.AgentDefinitions.ResolvedAgentDefinition definition)
    {
        return new AgentDefinitionViewModel(
            definition.Definition.Code,
            definition.Definition.Name,
            definition.Definition.Description,
            definition.Definition.Enabled,
            definition.Definition.CurrentVersion,
            definition.Version.Id,
            definition.Version.Version,
            definition.Version.Status,
            definition.Version.Name,
            definition.Version.Description,
            definition.Version.Instruction,
            definition.Version.SystemPromptTemplate,
            definition.Version.DefaultModel,
            AgentDefinitionToolListSerializer.Parse(definition.Version.AllowedTools),
            AgentDefinitionToolListSerializer.Parse(definition.Version.KnowledgeSources),
            definition.Version.MemoryPolicy,
            definition.Version.RoutingPolicy,
            definition.Version.ApprovalPolicy,
            definition.Version.ExecutionPolicy,
            definition.Version.PlannerPolicy,
            definition.Version.ContextPolicy,
            AgentDefinitionToolListSerializer.Parse(definition.Version.AllowedHandoffs),
            definition.Version.OutputSchema,
            definition.Version.MaxTurns,
            definition.Version.MaxCost,
            definition.Definition.CreateTime,
            definition.Definition.LastModifyTime,
            definition.Version.PublishedAt,
            AgentDefinitionToolListSerializer.Parse(definition.Version.DeniedTools));
    }
}
