namespace BestAgent.Api.Contracts.AgentRuns;

public record GetAgentRunChildResponse(
    string RunId,
    string AgentCode,
    string Status,
    string? Input,
    string? Output,
    DateTime CreateTime,
    DateTime LastModifyTime,
    DateTime? StartedAt,
    DateTime? EndedAt,
    int CurrentStepNo,
    string? ParentRunId,
    string? RootRunId,
    string? DelegatedByRunId,
    string? DelegatedByAgent,
    string? InterruptReason,
    string? WaitToken,
    string? CurrentStepId = null,
    string? WaitStepType = null,
    string? CurrentInvocationId = null,
    string? CurrentApprovalId = null,
    string? StreamUrl = null,
    ToolInvocationInfoResponse? CurrentToolInvocation = null,
    ApprovalInfoResponse? CurrentApproval = null,
    HumanWaitInfoResponse? CurrentHumanWait = null,
    HandoffInfoResponse? CurrentHandoff = null);
