namespace BestAgent.Api.Contracts.AgentDefinitions;

public record GetAgentDefinitionResponse(
    string Code,
    string Name,
    string? Description,
    bool Enabled,
    int CurrentVersion,
    string VersionId,
    int Version,
    string VersionStatus,
    string VersionName,
    string? VersionDescription,
    string? Instruction,
    string? SystemPromptTemplate,
    string DefaultModel,
    IReadOnlyList<string> AllowedTools,
    IReadOnlyList<string> KnowledgeSources,
    string? MemoryPolicy,
    string? RoutingPolicy,
    string? ApprovalPolicy,
    string? ExecutionPolicy,
    string? PlannerPolicy,
    string? ContextPolicy,
    IReadOnlyList<string> AllowedHandoffs,
    string? OutputSchema,
    int MaxTurns,
    decimal MaxCost,
    DateTime CreateTime,
    DateTime LastModifyTime,
    DateTime? PublishedAt,
    IReadOnlyList<string>? DeniedTools = null);
